version: '3.8'

services:
  client:
    image: 547206829132.dkr.ecr.eu-central-1.amazonaws.com/testhome
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - shared-networks
  server:
    image: 547206829132.dkr.ecr.eu-central-1.amazonaws.com/nestcloudapp
    ports:
      - 4000:4000
    restart: unless-stopped
    networks:
      - shared-networks

networks:
  shared-networks:
