version: '3.8'

services:
  client:
    image: public.ecr.aws/c2c2v5q6/testhome
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - shared-networks
  server:
    image: public.ecr.aws/c2c2v5q6/nestcloudapp
    ports:
      - 4000:4000
    restart: unless-stopped
    networks:
      - shared-networks

networks:
  shared-networks:


